name: Keep Streak Alive

on:
  schedule:
    - cron: '0 14 * * *' 
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo "Last run $(date -u)" > last_commit.txt
      - run: |
          git config user.name "wxn0brp-bot"
          git config user.email "wxn0brp@users.noreply.github.com"
          git add last_commit.txt
          git commit -m "Bot commit on $(date -u)"
          git push
